bot:
  # Owner ID of your account (can't be same as bot's ID)
  owner_id: 272402839874174976
  
  # Prefix you want bot commands to be triggered with
  prefix: ","
  
  # The word(s) you want the AI to respond to
  trigger: "Hey, Hello, Hi"

  # Model of the AI you'd like to use from Groq
  # Models to use from Groq (will fallback to next on rate limit)
  groq_models:
    - "meta-llama/llama-4-scout-17b-16e-instruct"
    - "llama-3.3-70b-versatile"
    - "openai/gpt-oss-120b"

  # Whether the bot should respond to DM's from people
  allow_dm: true

  # Whether the bot should be active in group chats
  allow_gc: true

  # Realistic Typing
  realistic_typing: true

  # Whether to wait and collect multiple messages before responding
  batch_messages: true 

  # Time before responding
  batch_wait_times:
    - time: 9       # quick reply, saw it immediately
      weight: 65
    - time: 20      # normal reply, took a few seconds to think
      weight: 20
    - time: 90      # slightly distracted
      weight: 10
    - time: 600     # 10 mins, actually busy
      weight: 4
    - time: 1600    # less than 30 mins, genuinely away
      weight: 1

  # Anti-detection settings
  ignore_chance: 0.03       # Chance to ignore a message
  typo_chance: 0.05         # Chance of a typo per message

  # Whether the bot should keep replying to people, even if there's no trigger
  hold_conversation: true
  
  # Anti Age Ban Measures
  anti_age_ban: false

  # Whether the help command should be usable by everyone or just the owner
  help_command_enabled: false

  # Disable the bot from being able to mention anyone
  disable_mentions: false

  # Whether the bot should ping on replies
  reply_ping: true

notifications:
  error_webhook: "" 
  ratelimit_notifications: true
